### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by kozaksv** [wagn/wagn#102]
Another problem with cyrillic.

Error message (visible to admin only)

File name too long - /home/a/production/tp_wiki/releases/20130520120452/tmp/cache/tp_wiki%2FCard%2F136924735234ip%2F%24%D0%9F%D1%83%D0%BB%D0%B0%D0%B2%D1%81%D1%8C%D0%BA%D0%B0_%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%96%D1%8F%2B%D0%BC%D0%BE%D0%B1%D1%96%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%2B*self20130522-25500-wg4th9.lock
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tempfile.rb:346:in `rmdir'
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tempfile.rb:346:in`rmdir'
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tempfile.rb:338:in `ensure in locking'
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tempfile.rb:338:in`locking'
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tempfile.rb:144:in `block in initialize'
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tmpdir.rb:133:in`create'
/home/a/.rbenv/versions/1.9.3-p327-perf/lib/ruby/1.9.1/tempfile.rb:134:in `initialize'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/core_ext/file/atomic.rb:19:in`new'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/core_ext/file/atomic.rb:19:in `atomic_write'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache/file_store.rb:91:in`write_entry'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:140:in `write_entry'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache.rb:364:in`block in write'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache.rb:520:in `instrument'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache.rb:362:in`write'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/cache.rb:123:in `write'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/fetch.rb:145:in`block in set_members'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/fetch.rb:135:in `map'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/fetch.rb:135:in`set_members'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/pattern.rb:68:in `set_names'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/pattern.rb:74:in`rule_set_keys'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/rules.rb:37:in `rule_card_id'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/rules.rb:32:in`rule_card'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/templating.rb:56:in `content_rule_card'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/templating.rb:31:in`template'
/home/a/production/tp_wiki/releases/20130520120452/lib/cardlib/templating.rb:42:in `hard_template'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:342:in`process_inclusion'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:303:in `expand_inclusion'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:206:in`block in process_content_object'
/home/a/production/tp_wiki/releases/20130520120452/lib/chunks/include.rb:75:in `process_chunk'
/home/a/production/tp_wiki/releases/20130520120452/lib/object_content.rb:119:in`block in process_content_object'
/home/a/production/tp_wiki/releases/20130520120452/lib/object_content.rb:107:in `block in each_chunk'
/home/a/production/tp_wiki/releases/20130520120452/lib/object_content.rb:107:in`each_chunk'
/home/a/production/tp_wiki/releases/20130520120452/lib/object_content.rb:119:in `process_content_object'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:205:in`process_content_object'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:194:in `process_content'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:213:in`block in edit_slot'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:212:in `map'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:212:in`edit_slot'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/set/all/rich_html.rb:261:in `block (4 levels) in '
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:315:in`block in card_form'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:112:in `block in method_missing'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:40:in`block in capture'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:40:in`capture'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/form_helper.rb:378:in `form_for'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:114:in`method_missing'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:315:in `card_form'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/set/all/rich_html.rb:258:in`block (3 levels) in '
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:198:in `block in wrap_content'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:112:in`block in method_missing'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:187:in`with_output_buffer'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:40:in `capture'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/tag_helper.rb:95:in`content_tag'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:114:in `method_missing'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:198:in`wrap_content'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/set/all/rich_html.rb:257:in `block (2 levels) in '
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:192:in`block in wrap'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:112:in `block in method_missing'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:40:in`block in capture'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:40:in`capture'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_view/helpers/tag_helper.rb:95:in `content_tag'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:114:in`method_missing'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer/html.rb:192:in `wrap'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/set/all/rich_html.rb:254:in`block in '
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/sets.rb:106:in `block (3 levels) in define_view'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:288:in`with_inclusion_mode'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/sets.rb:104:in `block (2 levels) in define_view'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/sets.rb:120:in`block (2 levels) in define_view'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:126:in `render'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/set/all/rich_html.rb:13:in`block in '
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/sets.rb:106:in `block (3 levels) in define_view'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/renderer.rb:288:in`with_inclusion_mode'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/sets.rb:104:in `block (2 levels) in define_view'
/home/a/production/tp_wiki/releases/20130520120452/lib/wagn/sets.rb:120:in`block (2 levels) in define_view'
/home/a/production/tp_wiki/releases/20130520120452/app/controllers/application_controller.rb:93:in `show'
/home/a/production/tp_wiki/releases/20130520120452/app/controllers/card_controller.rb:19:in`read'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in`process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:436:in `_run__4138813704040927769__process_action__2577927598290162581__callbacks'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`__run_callback'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in`run_callbacks'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in`process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in`block in instrument'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in`instrument'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in`process'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal.rb:203:in`dispatch'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal.rb:246:in`block in action'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in`block in call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/head.rb:14:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/params_parser.rb:21:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/flash.rb:242:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in`context'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/cookies.rb:341:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/query_cache.rb:64:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`_run__1362580917109867828__call__3009810355570047680__callbacks'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:27:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/airbrake-3.1.12/lib/airbrake/rails/middleware.rb:13:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/rack/logger.rb:32:in `call_app'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in`block in call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/tagged_logging.rb:22:in `tagged'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in`forward'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in`lookup'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/airbrake-3.1.12/lib/airbrake/user_informer.rb:16:in `_call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/airbrake-3.1.12/lib/airbrake/user_informer.rb:12:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:223:in`call'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:552:in`process_client'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:632:in `worker_loop'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:500:in`spawn_missing_workers'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:142:in `start'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/bin/unicorn:126:in`'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `load'
/home/a/production/tp_wiki/shared/bundle/ruby/1.9.1/bin/unicorn:23:in`

**Comment by gamicklisafisherr** [comment]
There is a limit of 256 characters on file names so it will obviously give problem. I guess long path utility can resolve this kind of issue as it is developed to handle this issue.

**Comment by ethn** [comment]
Right, I'm sure we can solve the problem if it's important to someone.  But the problem only shows up when using file caching, and file caching is really only intended for trials.  If you want to run a production site, you shouldn't use filed caching, you should use memcached or something faster.  (see http://wagn.org/wagn_in_production)

Is there someone who *really* needs to make this work with file caching?  I'd be interested to hear why upgrading to better caching isn't a better option.
