### ISSUE TITLE
/var/lib/gems/2.3.0/gems/wagn-1.20.2/lib/wagn/generators/wagn/wagn_generator.rb:259:in `valid_const?': uninitialized constant WagnGenerator::Error (NameError)

### ISSUE THREAD

**Issue by jfhbrook** [wagn/wagn#790]
Hello,

I don't know enough about wagn to know if this is a config issue or what, but I followed the "hard-mode" directions [here](http://wagn.org/get_started) inside a vagrant box (ubuntu xenial) and I get this when I try to `new`:

```
ubuntu@ubuntu-xenial:/vagrant$ wagn new wagn
Expected string default value for '--gem-path'; got false (boolean)
/var/lib/gems/2.3.0/gems/wagn-1.20.2/lib/wagn/generators/wagn/wagn_generator.rb:259:in `valid_const?': uninitialized constant WagnGenerator::Error (NameError)
Did you mean?  KeyError
               IOError
               Errno
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators/app_base.rb:137:in `create_root'
	from (eval):1:in `create_root'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/2.3.0/gems/wagn-1.20.2/lib/wagn/commands/application.rb:10:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/wagn-1.20.2/lib/wagn/cli.rb:16:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/wagn-1.20.2/bin/wagn:9:in `<top (required)>'
	from /usr/local/bin/wagn:23:in `load'
	from /usr/local/bin/wagn:23:in `<main>'
```

Any ideas?

**Comment by jfhbrook** [comment]
Realized the top line and the rest of it are unrelated--the first line is apparently a [thor deprecation warning](http://stackoverflow.com/a/41035588/1067530)

**Comment by jfhbrook** [comment]
Looks like I tripped up this code path by trying to name my wiki "wagn"

https://github.com/wagn/wagn/blob/master/wagn/lib/wagn/generators/wagn/wagn_generator.rb#L259

so I can work around this--still, kind of a weird error yeah?

**Comment by xithan** [comment]
I tried `rails new rails` and got `Invalid application name rails, constant Rails is already in use. Please choose another application name.` That's much more helpful than what wagn shows. I will fix that.

**Comment by xithan** [comment]
Actually, wagn tried to give the same error message as rails does but it failed because the exception class that it used to raise that error doesn't exist.
